// <auto-generated />
using DAL.Contexto;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(TecnicosDbContext))]
    [Migration("20240219014335_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Compartido.Dto.AlertaTecnico", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("cod_empresa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cod_solicitud")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("codtecnico")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("visto")
                        .HasColumnType("bit");

                    b.HasKey("id");

                    b.ToTable("AlertaTecnicos");
                });
#pragma warning restore 612, 618
        }
    }
}
